kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: cert-manager-repo
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitrepo-auth
  insecureSkipTLSVerify: false
  paths:
  - /cert-manager
  repo: https://github.com/estenrye/fleet.git
  serviceAccount: ""
  targets:
  - clusterSelector: {}
