- name: delete step-ca pods
  block:
    - name: list smallstep certificates pods
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: smallstep-ca
        label_selectors:
          app.kubernetes.io/name: step-certificates
      register: step_ca_pods

    - name: delete smallstep certificates pods
      community.kubernetes.k8s:
        state: absent
        api_version: "{{ item.api_version }}"
        kind: "{{ item.kind }}"
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      loop: "{{ step_ca_pods.resources }}"