apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare-dns01
spec:
  acme:
    email: esten.rye+acme@ryezone.com
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      key: tls-key
      name: cert-manager-issuer-secret
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cert-manager-issuer-secret
      selector:
        dnsZones:
        - rancher.ryezone.com