kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: git-repo
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitrepo-auth-xkfcf
  insecureSkipTLSVerify: false
  paths:
  - /GitRepo/default
  repo: https://github.com/estenrye/fleet.git
  serviceAccount: ""
  targets:
  - name: local
    clusterSelector:
      matchLabels:
        platform.ryezone.com/environment: local
