kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: git-repo
  namespace: fleet-local
spec:
  branch: main
  clientSecretName: gitrepo-auth
  insecureSkipTLSVerify: false
  paths:
  - /GitRepo/local
  repo: https://github.com/estenrye/fleet.git
  serviceAccount: ""
  targets:
  - clusterSelector: {}
