kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: GitRepo
  namespace: fleet-local
spec:
  branch: main
  clientSecretName: gitrepo-auth-mbv7p
  insecureSkipTLSVerify: false
  paths:
  - /GitRepo
  repo: https://github.com/estenrye/fleet.git
  serviceAccount: ""
  targets:
  - clusterSelector: {}
