all:
  hosts:
    jumpbox:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    kube_context: dev
    cert_manager_cloudflare_api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
    hpe_backend: 10.5.33.1