all:
  hosts:
    jumpbox:
      ansible_host: controlplane01.rancher.ryezone.com
      ansible_python_interpreter: /usr/bin/python3
  vars:
    platform_environment: rancher
    kube_context: default
    cert_manager_cloudflare_api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
    hpe_backend: nas.ryezone.com
