apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: global-whoami
  labels:
    ryezone.com/region: global
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:v1.6.1
        args:
          - -port
          - "8080"
        securityContext:
          runAsUser: 3000
          runAsGroup: 3000
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 150Mi
          requests:
            cpu: 500m
            memory: 25Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3