apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: global-whoami
  labels:
    app: whoami
    region: global
spec:
  selector:
    app: whoami
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080