- hosts: localhost
  tasks:
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: secrets/acme_issuer_key.key
      state: present
      return_content: true
    register: acme_issuer_key

- hosts: jumpbox
  tasks:
  - name: Configure Cloudflare API Key for cert-manager
    community.kubernetes.k8s:
      context: "{{ kube_context }}"
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: cert-manager-issuer-secret
          namespace: cert-manager
        type: Opaque
        stringData:
          api-token: "{{ cert_manager_cloudflare_api_token }}"
          tls-key: "{{ lookup('file', 'secrets/acme_issuer_key.key') }}"