- name: Install cert-manager secrets
  import_playbook: cert-manager-secrets.yml

- name: Install hpe-csi-secret.yml
  import_playbook:  truenas-csi.yml

- name: Install gitrepo-secrets.yml
  import_playbook: gitrepo-secrets.yml

