- hosts: jumpbox
  tasks:
  - name: Configure GitAuth Secret for Fleet
    community.kubernetes.k8s:
      context: "{{ kube_context }}"
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: gitrepo-auth
          namespace: "{{ item }}"
        type: kubernetes.io/basic-auth
        data:
          username: "{{ lookup('password', 'secrets/git_auth_user chars=ascii_letters,digits length=64') | b64encode }}"
          password: "{{ lookup('password', 'secrets/git_auth_password chars=ascii_letters,digits length=64') | b64encode }}"
    loop:
      - fleet-local
      - fleet-default