- hosts: jumpbox
  tasks:
  - name: Create the Kubernetes Namespace hpe-storage if it does not exist.
    community.kubernetes.k8s:
      context: "{{ kube_context }}"
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: hpe-storage

  - name: Configure hpe-csi Secret
    community.kubernetes.k8s:
      context: "{{ kube_context }}"
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: truenas-secret
          namespace: hpe-storage
        stringData:
          serviceName: truenas-csp-svc
          servicePort: "8080"
          username: hpe-csi
          password: "{{ lookup('password', 'files/secrets/hpe-csi_api_key chars=ascii_letters,digits length=64') | b64encode }}"
          backend: "{{ hpe_backend }}"
