- hosts: jumpbox
  tasks:
  - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: secrets/saml_authentication_idp.key
      state: present
      return_content: true
    register: saml_authentication_idp_key

  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: secrets/saml_authentication_idp.csr
      privatekey_path: secrets/saml_authentication_idp.key
      common_name: idp.ryezone.com

  - name: Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: secrets/saml_authentication_idp.crt
      privatekey_path: secrets/saml_authentication_idp.key
      csr_path: secrets/saml_authentication_idp.csr
      provider: selfsigned