kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm-repo-default
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: gitrepo-auth-xkfcf
  insecureSkipTLSVerify: false
  paths:
  - /helm-repo
  repo: https://github.com/estenrye/fleet.git
  serviceAccount: ""
  targets:
  - clusterSelector: {}
