apiVersion: catalog.cattle.io/v1
kind: App
metadata:
  name: cert-manager
  namespace: cert-manager
  chart:
    metadata:
      annotations:
        catalog.cattle.io/ui-source-repo: jetstack
        catalog.cattle.io/ui-source-repo-type: cluster
      version: v1.3.1
  helmVersion: 3
  values:
    prometheus:
      servicemonitor:
        enabled: true
